LanchesMac/Areas/Admin/Controllers/AdminOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LanchesMac.Context;
using LanchesMac.Models;
using Microsoft.AspNetCore.Authorization;
using ReflectionIT.Mvc.Paging;
using LanchesMac.ViewModels;

namespace LanchesMac.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class AdminOrderController : Controller
    {
        private readonly AppDbContext _context;

        public AdminOrderController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult SnacksOrder(int? id)
        {
            var order = _context.Orders
                .Include(pd => pd.OrderItems)
                .ThenInclude(l => l.Snack)
                .FirstOrDefault(p => p.OrderId == id);

            if (order == null)
            {
                Response.StatusCode = 404;
                return View("PedidoNotFound", id.Value);
            }

            SnackOrderViewModel snacksOrder = new SnackOrderViewModel()
            {
                Order = order,
                OrderDetails = order.OrderItems
            };

            return View(snacksOrder);
        }

        // GET: Admin/AdminOrder
        //public async Task<IActionResult> Index()
        //{
        //      return View(await _context.Orders.ToListAsync());
        //}

        public async Task<IActionResult> Index(string filter, int pageindex = 1, string sort = "Name")
        {
            var result = _context.Orders.AsNoTracking().AsQueryable();

            if (!string.IsNullOrWhiteSpace(filter))
            {
                result = result.Where(p => p.Name.Contains(filter));
            }

            var model = await PagingList.CreateAsync(result, 5, pageindex, sort, "Name");
            model.RouteValue = new RouteValueDictionary { { "filter", filter } };

            return View(model);
        }

        // GET: Admin/AdminOrder/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Admin/AdminOrder/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminOrder/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,Name,Lastname,Address1,Address2,ZipCode,State,City,Telephone,Email,OrderDispatched,OrderDeliveredIn")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Admin/AdminOrder/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Admin/AdminOrder/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,Name,Lastname,Address1,Address2,ZipCode,State,City,Telephone,Email,OrderDispatched,OrderDeliveredIn")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Admin/AdminOrder/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Admin/AdminOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'AppDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

LanchesMac/Areas/Admin/Views/AdminOrder/Create.cshtml
@model LanchesMac.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h4>Criar Pedido</h4>
<hr />

<form asp-action="Create" role="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="form-group col-sm-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-6">
            <label asp-for="Lastname" class="control-label"></label>
            <input asp-for="Lastname" class="form-control" />
            <span asp-validation-for="Lastname" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Address1" class="control-label"></label>
        <input asp-for="Address1" class="form-control" />
        <span asp-validation-for="Address1" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address2" class="control-label"></label>
        <input asp-for="Address2" class="form-control" />
        <span asp-validation-for="Address2" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="form-group col-sm-6">
            <label asp-for="ZipCode" class="control-label"></label>
            <input asp-for="ZipCode" class="form-control" />
            <span asp-validation-for="ZipCode" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-6">
            <label asp-for="State" class="control-label"></label>
            <input asp-for="State" class="form-control" />
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="City" class="control-label"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Telephone" class="control-label"></label>
        <input asp-for="Telephone" class="form-control" />
        <span asp-validation-for="Telephone" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="form-group col-sm-6">
            <label asp-for="OrderDispatched" class="control-label"></label>
            <input asp-for="OrderDispatched" class="form-control" />
            <span asp-validation-for="OrderDispatched" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-6">
            <label asp-for="OrderDeliveredIn" class="control-label"></label>
            <input asp-for="OrderDeliveredIn" class="form-control" />
            <span asp-validation-for="OrderDeliveredIn" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-outline-info">Retornar</a>
    </div>
</form>
   

LanchesMac/Areas/Admin/Views/AdminOrder/Delete.cshtml
@model LanchesMac.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h2>Deseja deletar este pedido ?</h2>
<br />
<h3><strong>Atenção !!! Ao deletar o pedido seus itens serão excluídos</strong></h3>
<hr />
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDispatched)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDispatched)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDeliveredIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDeliveredIn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-outline-info">Retornar</a>
    </form>
</div>

LanchesMac/Areas/Admin/Views/AdminOrder/Details.cshtml
@model LanchesMac.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h3>Detalhes do Pedido</h3>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDispatched)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDispatched)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDeliveredIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDeliveredIn)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.OrderId" class="btn btn-primary">Editar</a> |
    <a asp-action="Index" class="btn btn-outline-info">Retornar</a>
</div>

LanchesMac/Areas/Admin/Views/AdminOrder/Edit.cshtml
@model LanchesMac.Models.Order

@{
    ViewData["Title"] = "Edit";
}


<h3>Editar Pedido</h3>
<h4>(Não inclui itens do pedido)</h4>
<hr />


<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="OrderId" />

    <div class="row">
        <div class="form-group col-sm-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-6">
            <label asp-for="Lastname" class="control-label"></label>
            <input asp-for="Lastname" class="form-control" />
            <span asp-validation-for="Lastname" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Address1" class="control-label"></label>
        <input asp-for="Address1" class="form-control" />
        <span asp-validation-for="Address1" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address2" class="control-label"></label>
        <input asp-for="Address2" class="form-control" />
        <span asp-validation-for="Address2" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="form-group">
            <label asp-for="ZipCode" class="control-label"></label>
            <input asp-for="ZipCode" class="form-control" />
            <span asp-validation-for="ZipCode" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="State" class="control-label"></label>
            <input asp-for="State" class="form-control" />
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="City" class="control-label"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Telephone" class="control-label"></label>
        <input asp-for="Telephone" class="form-control" />
        <span asp-validation-for="Telephone" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="form-group col-sm-6">
            <label asp-for="OrderDispatched" class="control-label"></label>
            <input asp-for="OrderDispatched" class="form-control" />
            <span asp-validation-for="OrderDispatched" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-6">
            <label asp-for="OrderDeliveredIn" class="control-label"></label>
            <input asp-for="OrderDeliveredIn" class="form-control" />
            <span asp-validation-for="OrderDeliveredIn" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-outline-info">Retornar</a>
    </div>
</form>

LanchesMac/Areas/Admin/Views/AdminOrder/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<LanchesMac.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Pedidos</h1>

<form method="get" class="form-inline">
    <input name="filter" class="form-control" placeholder="filtro" 
    value="@Model.RouteValue["Filter"]"/>
    <button type="submit" class="btn btn-info">Procurar</button>
</form>

Total de Pedidos : @Model.TotalRecordCount
<div>
    <vc:pager paging-list="@Model"></vc:pager>
</div>

<p>
    <a asp-action="Create">Criar Novo Pedido</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telephone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDispatched)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDeliveredIn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDispatched)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDeliveredIn)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.OrderId">Deletar</a> |
                <a asp-action="SnacksOrder" asp-route-id="@item.OrderId">Ver Itens</a>
            </td>
        </tr>
}
    </tbody>
</table>

LanchesMac/Areas/Admin/Views/AdminOrder/PedidoNotFound.cshtml
@model int

@{
    ViewData["Title"] = "404 Not Found";
}

<div class="alert alert-danger mt-1 mb-1">
    <h1>Error 404 - Not Found</h1>
    <hr />
    <h2>Pedido com o id = @Model não foi encontrado</h2>
</div>

<a asp-action="Index" asp-controller="AdminOrder" class="btn btn-outline-success">
    <h2>Retornar para a lista de pedidos</h2>
</a>

LanchesMac/Areas/Admin/Views/AdminOrder/snacksOrder.cshtml
@model LanchesMac.ViewModels.SnackOrderViewModel

@{
    ViewData["Title"] = "SnacksOrders";
    decimal totalOrder = 0;
}

<h1>Lanches do Pedido</h1>
<hr />

<h3>Pedido : @Html.DisplayFor(model => @Model.Order.OrderId)</h3>
<h3>Pedido : @Html.DisplayFor(model => @Model.Order.Name)</h3>
<h3>Pedido : @Html.DisplayFor(model => @Model.Order.OrderDispatched)</h3>
<h3>Pedido : @Html.DisplayFor(model => @Model.Order.OrderDeliveredIn)</h3>

<table class="table">
    @foreach (var item in @Model.Order.OrderItems)
    {
        totalOrder += (item.Snack.Price * item.Quantity);
        <tr>
            <td align="right">
                <h3>@Html.DisplayFor(modelItem => item.Snack.SnackName)</h3>
            </td>
            <td align="right">
                <img src="@item.Snack.ImageUrl" class="img-fluid" height="100" width="100">
            </td>
            <td align="right">
                <h3>@string.Format("{0:C}", item.Snack.Price)</h3>
            </td>
            <td align="right">
                <h3>(@Html.DisplayFor(modelItem => item.Quantity))</h3>
            </td>
        </tr>
    }
    <tr>
        <td colspan="2">&nbsp;</td>
        <td align="right">
            <h3>Total do pedido : @string.Format("{0:C}", totalOrder)</h3>
        </td>
    </tr>
</table>
<a asp-action="Index" class="btn btn-outline-info">Retornar</a>