LanchesMac/Areas/Admin/Controllers/AdminChartController.cs
using LanchesMac.Areas.Admin.Services;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminChartController : Controller
    {
        private readonly ChartSalesService _chartSalesService;

        public AdminChartController(ChartSalesService chartSalesService)
        {
            _chartSalesService = chartSalesService ?? throw new ArgumentNullException(nameof(chartSalesService));
        }

        public JsonResult SnacksSales (int days)
        {
            var snacksTotalSales = _chartSalesService.GetSnacksSales(days);
            return Json(snacksTotalSales);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult MonthlySales()
        {
            return View();
        }

        [HttpGet]
        public IActionResult WeeklySales()
        {
            return View();
        }
    }
}

LanchesMac/Areas/Admin/Views/AdminChart/Index.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(LoadData);

    function LoadData() {
        $.ajax({
            url: '@Url.Action("SnacksSales", "AdminChart")',
            data: { days: 360 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                SnackSalesChart(data);
                return false;
            }
        });
        return false;
    }

    function SnackSalesChart(data) {
        var dataArray = [
            [{label: 'Lanche', type: 'string'},
            {label: 'Quantidade', type: 'number' },
            {label: 'Valores(R$)', type: 'number' }]
        ];
        $.each(data, function (i, item) {
            dataArray.push([item.snackName, item.snackQuantity, item.snackTotalValue]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 360 dias',

            animation: {
                duration: 3000,
                easing: 'out',
                startup: true
            },

            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };
        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>

LanchesMac/Areas/Admin/Views/AdminChart/MonthlySales.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(LoadData);

    //obter os dados
    function LoadData() {
        $.ajax({
            url: '@Url.Action("SnacksSales", "AdminChart")',
            data: { days: 30 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                SnackSalesChart(data);
                return false;
            }
        });
        return false;
    }

    function SnackSalesChart(data) {
        var dataArray = [
            [{ label: 'Lanche', type: 'string' },
            { label: 'Quantidade', type: 'number' },
            { label: 'Valores(R$)', type: 'number' }]
        ];
        $.each(data, function (i, item) {
            dataArray.push([item.snackNames, item.snackQuantity, item.snackTotalValue]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 30 dias',
            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };

        //preparar a visualização e definindo o tipo de gráfico
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>

LanchesMac/Areas/Admin/Views/AdminChart/WeeklySales.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(LoadData);

    function LoadData() {
        $.ajax({
            url: '@Url.Action("SnacksSales", "AdminChart")',
            data: { days: 7 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                SnackSalesChart(data);
                return false;
            }
        });
        return false;
    }

    function SnackSalesChart(data) {
        var dataArray = [
            [{ label: 'Lanche', type: 'string' },
            { label: 'Quantidade', type: 'number' },
            { label: 'Valores(R$)', type: 'number' }]
        ];
        $.each(data, function (i, item) {
            dataArray.push([item.snackName, item.snackQuantity, item.snackTotalValue]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 7 dias',

            curveType: 'function',
            legend: {position: 'bottom'},

            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>